name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      AT_USERNAME: ${{ secrets.USER }}
      AT_PASSWORD: ${{ secrets.PASS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Install Browsers
        run: npx playwright install --with-deps chromium
      - name: Run API tests
        run: npx playwright test -g api
      - name: Run e2e tests
        run: npx playwright test -g auth
